{% set name = "macrel" %}
{% set version = "0.1" %}

package:
  name: {{ name }}
  version: {{ version }}
  
source:
  git_url: https://github.com/BigDataBiology/macrel

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  run:
    - python
    - ngless
    - megahit
    - paladin
    - pandas
    - rpy2
    - tzlocal
    - r-base
    - r-essentials
    - r-peptides
    - r-randomforest

about:
  home: https://github.com/BigDataBiology/macrel
  license: MIT
  summary: "a module for AMP (antimicrobial peptide) prediction"
  description: |
    Used for the prediction of AMPs in (meta)genomes.
  dev_url: https://github.com/BigDataBiology/macrel
  
extra:
  recipe-maintainers:
    - HiramHe
