site_name: "MACREL"
repo_url: "https://github.com/BigDataBiology/macrel"
repo_name: "GitHub"
edit_url: null # Eliminate edit button
copyright: "All rights reserved"
google_analytics: ['UA-36723568-3', 'mkdocs.org']

theme:
    name: readthedocs
    highlightjs: true
    html_show_sourcelink: false
    prev_next_buttons_location: both
    hljs_languages:
        - yaml
        - rust
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s        
        
nav:
    - 'Macrel': index.md
    - 'Install': install.md
    - 'Usage': usage.md
    - 'What's New (history)': novelty.md
    - 'Contacts': contact.md
    - 'Cite us': cite.md

