site_name: "MACREL"
repo_url: "https://github.com/BigDataBiology/macrel"

nav:
    - 'Macrel': index.md
    - 'Install': install.md
    - 'Usage': usage.md
    - "What's New (history)": novelty.md
    - 'Cite': cite.md

