#!/bin/bash

######################### Hint ########################################
## Run as: qsub job.script
#######################################################################

######################## PBS Script ###################################
# Job Name
#PBS -N 1_cel_test
# Merge output and error files
#PBS -j oe
#PBS -l walltime=1:00:00
#PBS -l select=mem=28GB
#PBS -l select=arch=linux
# Select 8 nodes with 1 CPU each using 4Gb
#PBS -l select=8:ncpus=1:mem=4GB 
#PBS -l place=free
# Export Users Environmental Variables to Execution Host
#PBS -V
# Send email on abort, begin and end
#PBS -m abe
# Specify mail recipient
#PBS -M celio.diasjunior@gmail.com
#######################################################################

######################### CMDs ########################################

/home1/celiodias/FACS/FACS17v2.sh -m c --fasta /home1/celiodias/Desktop/benchmark/analysis/metagenome/test.contigs.fna.gz -t 7 --block 100M --log test.log --outfolder /home1/celiodias/Desktop/benchmark/analysis/metagenome/ --outtag script_test_qsub

