#!/bin/bash

######################### Hint ########################################
## Run as: qsub job.script
#######################################################################

######################## PBS Script ###################################
# Job Name
#PBS -N facs_test
# Merge output and error files
#PBS -j oe
#PBS -l walltime=1:00:00
#PBS -l select=mem=28GB
#PBS -l select=arch=linux
# Select 8 nodes with 1 CPU each using 4Gb
#PBS -l select=8:ncpus=1:mem=4GB 
#PBS -l place=free
# Export Users Environmental Variables to Execution Host
#PBS -V
# Send email on abort, begin and end
#PBS -m abe
# Specify mail recipient
#PBS -M xxx@Email.com
#######################################################################

######################### CMDs ########################################

FACS-master/FACS17v2.sh -m c --fasta /path/to/test.contigs.fna.gz -t 7 --block 100M --log test.log --outfolder /path/to/output/ --outtag script_test_qsub --tmp TEMP

