name: Build Status
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checking code
      uses: actions/checkout@v2

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
 
    - name: Build environment
      run: |
        PYTHON_VERSION=${{ matrix.python-version }} ./install.sh
        mamba install --prefix ./envs/Macrel_env  -y pytest

    - name: Test Macrel
      run: |
        source /usr/share/miniconda3/bin/activate envs/Macrel_env/
        ./run-tests.sh
        python -m pytest macrel/tests
