name: Build Status

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
    - name: Checking code
      uses: actions/checkout@v3

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}
      run : |
        conda install -c bioconda -c conda-forge \
          ngless pyrodigal megahit paladin pandas atomium tzlocal \
          "scikit-learn<1.3.0" "joblib<1.3.0"
        conda install pytest
        pip install .
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        python -m pytest macrel/tests

    - name: Test Macrel CLI
      shell: bash -l {0}
      run: |
        ./run-tests.sh
