name: Build Status
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
    - name: Checking code
      uses: actions/checkout@v3

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
 
    - name: Build environment
      run: |
        conda install -y mamba -n base -c conda-forge
        PYTHON_VERSION=${{ matrix.python-version }} ./install.sh
        source /usr/share/miniconda3/bin/activate envs/Macrel_env/
        # Using conda/mamba to install pytest can cause other packages to be downgraded!
        pip install pytest

    - name: Test Macrel
      run: |
        source /usr/share/miniconda3/bin/activate envs/Macrel_env/
        ./run-tests.sh
        python -m pytest macrel/tests
