name: Build Status
   
on:
   push:
   pull_request:

defaults:
  run:
    shell: bash # To ensure that the environment will always return to bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
            
    - name: Checking code
      uses: actions/checkout@v2
  
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-activate-base: true
        activate-environment: ""
 
    - name: Build and test environment
      run: |
        ./install.sh
        conda install --prefix ./envs/Macrel_env  -y pytest

    - name: Evaluate Macrel Build
      run: |
        source /usr/share/miniconda3/bin/activate /home/runner/work/macrel/macrel/envs/Macrel_env
        macrel="/home/runner/work/macrel/macrel/envs/Macrel_env/bin/macrel"
        ./run-tests.sh
        python -m pytest macrel/tests
